# Generated by Django 3.1.2 on 2020-10-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201019_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='usr',
            new_name='user',
        ),
    ]
