# Generated by Django 3.1.2 on 2020-10-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '__first__'),
        ('accounts', '0003_auto_20201019_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='next',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prev',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_visited_word',
            field=models.ForeignKey(default=4760, on_delete=django.db.models.deletion.CASCADE, to='words.word'),
        ),
    ]
